### ISSUE TITLE
第1回 2019/06/07 Fri

### ISSUE THREAD

**Issue by chez-shanpu** [chez-shanpu/ResearchTalkDay#1]
- 日時：2019/06/07 Fri　17:00~18:00
- 場所：8-302

コメントに発表したい内容を簡単に書いてください．

発表者は10分程度を目安に自由に喋ってください．
発表終了後，聞いてる人との質疑応答等を行うトーク時間を設けます．

プロジェクターとスクリーンのある部屋を用意できるようがんばります．

**Comment by chez-shanpu** [comment]
輪講，一回目の自分の番が来ているはずなのでそれについてしゃべる

**Comment by tjmtmmnk** [comment]
Ques-Chain: Ethereum Based E-Voting Sytemについて話す
https://tjmtmmnk.hatenablog.com/entry/2019/05/21/153131

**Comment by ocucraqp** [comment]
indexとhashについて話す

**Comment by tjmtmmnk** [comment]
https://book.ethereum-jp.net
オススメ

**Comment by chez-shanpu** [comment]
次回は7月くらいにやりたいな
