### ISSUE TITLE
第2回 2019/11/25 Mon

### ISSUE THREAD

**Issue by chez-shanpu** [chez-shanpu/ResearchTalkDay#2]
- 日時：2019/11/25 Mon　16:30~17:30
- 場所：8-302

コメントに発表したい内容を簡単に書いてください．

発表者は10分程度を目安に自由に喋ってください．
発表終了後，聞いてる人との質疑応答等を行うトーク時間を設けます．

**Comment by tjmtmmnk** [comment]
プロキシ再暗号化を使った電子投票
https://tjmtmmnk.hatenablog.com/entry/2019/11/05/164709

**Comment by LakeRainSound** [comment]
GitHub starをつける動機とそのバズり方に関する調査
https://arxiv.org/abs/1811.07643

**Comment by tjmtmmnk** [comment]
ethereumをゾンビゲームを通じて勉強する
https://cryptozombies.io/jp/course/
